sudo: required
language: node_js
node_js:
  - stable
  - 6
  - 5
  - 4
  #- 0.12
  #- 0.11

services:
  - docker

before_script:
  - docker-compose up -d
  - gulp createTravisOrmConfig

after_success:
  - bash <(curl -s https://codecov.io/bash)